/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth-status'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiGiftCodesRouteImport } from './routes/api/gift-codes'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as InvIdRouteImport } from './routes/inv.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGiftCodesRedeemRouteImport } from './routes/api/gift-codes/redeem'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices.$id'
import { Route as ApiMcpTokensRouteImport } from './routes/api/mcp/tokens'
import { Route as ApiProCheckoutRouteImport } from './routes/api/pro/checkout'
import { Route as ApiProStatusRouteImport } from './routes/api/pro/status'
import { Route as ApiRecurringProcessRouteImport } from './routes/api/recurring/process'
import { Route as ApiReferralsAttributeRouteImport } from './routes/api/referrals/attribute'
import { Route as ApiReferralsMineRouteImport } from './routes/api/referrals/mine'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'
import { Route as ApiWebhooksRazorpayPlatformRouteImport } from './routes/api/webhooks/razorpay-platform'
import { Route as ApiMcpTokensIdRouteImport } from './routes/api/mcp/tokens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth-status',
  path: '/api/auth-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGiftCodesRoute = ApiGiftCodesRouteImport.update({
  id: '/api/gift-codes',
  path: '/api/gift-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const InvIdRoute = InvIdRouteImport.update({
  id: '/inv/$id',
  path: '/inv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGiftCodesRedeemRoute = ApiGiftCodesRedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => ApiGiftCodesRoute,
} as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiMcpTokensRoute = ApiMcpTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => ApiMcpRoute,
} as any)
const ApiProCheckoutRoute = ApiProCheckoutRouteImport.update({
  id: '/api/pro/checkout',
  path: '/api/pro/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProStatusRoute = ApiProStatusRouteImport.update({
  id: '/api/pro/status',
  path: '/api/pro/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecurringProcessRoute = ApiRecurringProcessRouteImport.update({
  id: '/api/recurring/process',
  path: '/api/recurring/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsAttributeRoute = ApiReferralsAttributeRouteImport.update({
  id: '/api/referrals/attribute',
  path: '/api/referrals/attribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralsMineRoute = ApiReferralsMineRouteImport.update({
  id: '/api/referrals/mine',
  path: '/api/referrals/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayPlatformRoute =
  ApiWebhooksRazorpayPlatformRouteImport.update({
    id: '/api/webhooks/razorpay-platform',
    path: '/api/webhooks/razorpay-platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMcpTokensIdRoute = ApiMcpTokensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMcpTokensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/gift-codes': typeof ApiGiftCodesRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/inv/$id': typeof InvIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gift-codes/redeem': typeof ApiGiftCodesRedeemRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/mcp/tokens': typeof ApiMcpTokensRouteWithChildren
  '/api/pro/checkout': typeof ApiProCheckoutRoute
  '/api/pro/status': typeof ApiProStatusRoute
  '/api/recurring/process': typeof ApiRecurringProcessRoute
  '/api/referrals/attribute': typeof ApiReferralsAttributeRoute
  '/api/referrals/mine': typeof ApiReferralsMineRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/razorpay-platform': typeof ApiWebhooksRazorpayPlatformRoute
  '/api/mcp/tokens/$id': typeof ApiMcpTokensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/gift-codes': typeof ApiGiftCodesRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/inv/$id': typeof InvIdRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gift-codes/redeem': typeof ApiGiftCodesRedeemRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/mcp/tokens': typeof ApiMcpTokensRouteWithChildren
  '/api/pro/checkout': typeof ApiProCheckoutRoute
  '/api/pro/status': typeof ApiProStatusRoute
  '/api/recurring/process': typeof ApiRecurringProcessRoute
  '/api/referrals/attribute': typeof ApiReferralsAttributeRoute
  '/api/referrals/mine': typeof ApiReferralsMineRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/razorpay-platform': typeof ApiWebhooksRazorpayPlatformRoute
  '/api/mcp/tokens/$id': typeof ApiMcpTokensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/api/auth-status': typeof ApiAuthStatusRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/gift-codes': typeof ApiGiftCodesRouteWithChildren
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/api/mcp': typeof ApiMcpRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/inv/$id': typeof InvIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/gift-codes/redeem': typeof ApiGiftCodesRedeemRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/mcp/tokens': typeof ApiMcpTokensRouteWithChildren
  '/api/pro/checkout': typeof ApiProCheckoutRoute
  '/api/pro/status': typeof ApiProStatusRoute
  '/api/recurring/process': typeof ApiRecurringProcessRoute
  '/api/referrals/attribute': typeof ApiReferralsAttributeRoute
  '/api/referrals/mine': typeof ApiReferralsMineRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
  '/api/webhooks/razorpay-platform': typeof ApiWebhooksRazorpayPlatformRoute
  '/api/mcp/tokens/$id': typeof ApiMcpTokensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/auth-status'
    | '/api/checkout'
    | '/api/gift-codes'
    | '/api/invoices'
    | '/api/mcp'
    | '/app/clients'
    | '/app/invoices'
    | '/app/settings'
    | '/inv/$id'
    | '/app/'
    | '/api/auth/$'
    | '/api/gift-codes/redeem'
    | '/api/invoices/$id'
    | '/api/mcp/tokens'
    | '/api/pro/checkout'
    | '/api/pro/status'
    | '/api/recurring/process'
    | '/api/referrals/attribute'
    | '/api/referrals/mine'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/razorpay-platform'
    | '/api/mcp/tokens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/auth-status'
    | '/api/checkout'
    | '/api/gift-codes'
    | '/api/invoices'
    | '/api/mcp'
    | '/app/clients'
    | '/app/invoices'
    | '/app/settings'
    | '/inv/$id'
    | '/app'
    | '/api/auth/$'
    | '/api/gift-codes/redeem'
    | '/api/invoices/$id'
    | '/api/mcp/tokens'
    | '/api/pro/checkout'
    | '/api/pro/status'
    | '/api/recurring/process'
    | '/api/referrals/attribute'
    | '/api/referrals/mine'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/razorpay-platform'
    | '/api/mcp/tokens/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/api/auth-status'
    | '/api/checkout'
    | '/api/gift-codes'
    | '/api/invoices'
    | '/api/mcp'
    | '/app/clients'
    | '/app/invoices'
    | '/app/settings'
    | '/inv/$id'
    | '/app/'
    | '/api/auth/$'
    | '/api/gift-codes/redeem'
    | '/api/invoices/$id'
    | '/api/mcp/tokens'
    | '/api/pro/checkout'
    | '/api/pro/status'
    | '/api/recurring/process'
    | '/api/referrals/attribute'
    | '/api/referrals/mine'
    | '/api/webhooks/razorpay'
    | '/api/webhooks/razorpay-platform'
    | '/api/mcp/tokens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiGiftCodesRoute: typeof ApiGiftCodesRouteWithChildren
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  ApiMcpRoute: typeof ApiMcpRouteWithChildren
  InvIdRoute: typeof InvIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProCheckoutRoute: typeof ApiProCheckoutRoute
  ApiProStatusRoute: typeof ApiProStatusRoute
  ApiRecurringProcessRoute: typeof ApiRecurringProcessRoute
  ApiReferralsAttributeRoute: typeof ApiReferralsAttributeRoute
  ApiReferralsMineRoute: typeof ApiReferralsMineRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
  ApiWebhooksRazorpayPlatformRoute: typeof ApiWebhooksRazorpayPlatformRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-status': {
      id: '/api/auth-status'
      path: '/api/auth-status'
      fullPath: '/api/auth-status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gift-codes': {
      id: '/api/gift-codes'
      path: '/api/gift-codes'
      fullPath: '/api/gift-codes'
      preLoaderRoute: typeof ApiGiftCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/inv/$id': {
      id: '/inv/$id'
      path: '/inv/$id'
      fullPath: '/inv/$id'
      preLoaderRoute: typeof InvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gift-codes/redeem': {
      id: '/api/gift-codes/redeem'
      path: '/redeem'
      fullPath: '/api/gift-codes/redeem'
      preLoaderRoute: typeof ApiGiftCodesRedeemRouteImport
      parentRoute: typeof ApiGiftCodesRoute
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/mcp/tokens': {
      id: '/api/mcp/tokens'
      path: '/tokens'
      fullPath: '/api/mcp/tokens'
      preLoaderRoute: typeof ApiMcpTokensRouteImport
      parentRoute: typeof ApiMcpRoute
    }
    '/api/pro/checkout': {
      id: '/api/pro/checkout'
      path: '/api/pro/checkout'
      fullPath: '/api/pro/checkout'
      preLoaderRoute: typeof ApiProCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pro/status': {
      id: '/api/pro/status'
      path: '/api/pro/status'
      fullPath: '/api/pro/status'
      preLoaderRoute: typeof ApiProStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recurring/process': {
      id: '/api/recurring/process'
      path: '/api/recurring/process'
      fullPath: '/api/recurring/process'
      preLoaderRoute: typeof ApiRecurringProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals/attribute': {
      id: '/api/referrals/attribute'
      path: '/api/referrals/attribute'
      fullPath: '/api/referrals/attribute'
      preLoaderRoute: typeof ApiReferralsAttributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referrals/mine': {
      id: '/api/referrals/mine'
      path: '/api/referrals/mine'
      fullPath: '/api/referrals/mine'
      preLoaderRoute: typeof ApiReferralsMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay-platform': {
      id: '/api/webhooks/razorpay-platform'
      path: '/api/webhooks/razorpay-platform'
      fullPath: '/api/webhooks/razorpay-platform'
      preLoaderRoute: typeof ApiWebhooksRazorpayPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/tokens/$id': {
      id: '/api/mcp/tokens/$id'
      path: '/$id'
      fullPath: '/api/mcp/tokens/$id'
      preLoaderRoute: typeof ApiMcpTokensIdRouteImport
      parentRoute: typeof ApiMcpTokensRoute
    }
  }
}

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiGiftCodesRouteChildren {
  ApiGiftCodesRedeemRoute: typeof ApiGiftCodesRedeemRoute
}

const ApiGiftCodesRouteChildren: ApiGiftCodesRouteChildren = {
  ApiGiftCodesRedeemRoute: ApiGiftCodesRedeemRoute,
}

const ApiGiftCodesRouteWithChildren = ApiGiftCodesRoute._addFileChildren(
  ApiGiftCodesRouteChildren,
)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

interface ApiMcpTokensRouteChildren {
  ApiMcpTokensIdRoute: typeof ApiMcpTokensIdRoute
}

const ApiMcpTokensRouteChildren: ApiMcpTokensRouteChildren = {
  ApiMcpTokensIdRoute: ApiMcpTokensIdRoute,
}

const ApiMcpTokensRouteWithChildren = ApiMcpTokensRoute._addFileChildren(
  ApiMcpTokensRouteChildren,
)

interface ApiMcpRouteChildren {
  ApiMcpTokensRoute: typeof ApiMcpTokensRouteWithChildren
}

const ApiMcpRouteChildren: ApiMcpRouteChildren = {
  ApiMcpTokensRoute: ApiMcpTokensRouteWithChildren,
}

const ApiMcpRouteWithChildren =
  ApiMcpRoute._addFileChildren(ApiMcpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiGiftCodesRoute: ApiGiftCodesRouteWithChildren,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  ApiMcpRoute: ApiMcpRouteWithChildren,
  InvIdRoute: InvIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProCheckoutRoute: ApiProCheckoutRoute,
  ApiProStatusRoute: ApiProStatusRoute,
  ApiRecurringProcessRoute: ApiRecurringProcessRoute,
  ApiReferralsAttributeRoute: ApiReferralsAttributeRoute,
  ApiReferralsMineRoute: ApiReferralsMineRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
  ApiWebhooksRazorpayPlatformRoute: ApiWebhooksRazorpayPlatformRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
