/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiInvoicesRouteImport } from './routes/api/invoices'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as InvIdRouteImport } from './routes/inv.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInvoicesIdRouteImport } from './routes/api/invoices.$id'
import { Route as ApiRecurringProcessRouteImport } from './routes/api/recurring/process'
import { Route as ApiWebhooksRazorpayRouteImport } from './routes/api/webhooks/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesRoute = ApiInvoicesRouteImport.update({
  id: '/api/invoices',
  path: '/api/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const InvIdRoute = InvIdRouteImport.update({
  id: '/inv/$id',
  path: '/inv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesIdRoute = ApiInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiInvoicesRoute,
} as any)
const ApiRecurringProcessRoute = ApiRecurringProcessRouteImport.update({
  id: '/api/recurring/process',
  path: '/api/recurring/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksRazorpayRoute = ApiWebhooksRazorpayRouteImport.update({
  id: '/api/webhooks/razorpay',
  path: '/api/webhooks/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/inv/$id': typeof InvIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/recurring/process': typeof ApiRecurringProcessRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/inv/$id': typeof InvIdRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/recurring/process': typeof ApiRecurringProcessRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/invoices': typeof ApiInvoicesRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/inv/$id': typeof InvIdRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/invoices/$id': typeof ApiInvoicesIdRoute
  '/api/recurring/process': typeof ApiRecurringProcessRoute
  '/api/webhooks/razorpay': typeof ApiWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/checkout'
    | '/api/invoices'
    | '/app/clients'
    | '/app/invoices'
    | '/app/settings'
    | '/inv/$id'
    | '/app/'
    | '/api/auth/$'
    | '/api/invoices/$id'
    | '/api/recurring/process'
    | '/api/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/checkout'
    | '/api/invoices'
    | '/app/clients'
    | '/app/invoices'
    | '/app/settings'
    | '/inv/$id'
    | '/app'
    | '/api/auth/$'
    | '/api/invoices/$id'
    | '/api/recurring/process'
    | '/api/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/api/checkout'
    | '/api/invoices'
    | '/app/clients'
    | '/app/invoices'
    | '/app/settings'
    | '/inv/$id'
    | '/app/'
    | '/api/auth/$'
    | '/api/invoices/$id'
    | '/api/recurring/process'
    | '/api/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiInvoicesRoute: typeof ApiInvoicesRouteWithChildren
  InvIdRoute: typeof InvIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRecurringProcessRoute: typeof ApiRecurringProcessRoute
  ApiWebhooksRazorpayRoute: typeof ApiWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices': {
      id: '/api/invoices'
      path: '/api/invoices'
      fullPath: '/api/invoices'
      preLoaderRoute: typeof ApiInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/inv/$id': {
      id: '/inv/$id'
      path: '/inv/$id'
      fullPath: '/inv/$id'
      preLoaderRoute: typeof InvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/$id': {
      id: '/api/invoices/$id'
      path: '/$id'
      fullPath: '/api/invoices/$id'
      preLoaderRoute: typeof ApiInvoicesIdRouteImport
      parentRoute: typeof ApiInvoicesRoute
    }
    '/api/recurring/process': {
      id: '/api/recurring/process'
      path: '/api/recurring/process'
      fullPath: '/api/recurring/process'
      preLoaderRoute: typeof ApiRecurringProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/razorpay': {
      id: '/api/webhooks/razorpay'
      path: '/api/webhooks/razorpay'
      fullPath: '/api/webhooks/razorpay'
      preLoaderRoute: typeof ApiWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiInvoicesRouteChildren {
  ApiInvoicesIdRoute: typeof ApiInvoicesIdRoute
}

const ApiInvoicesRouteChildren: ApiInvoicesRouteChildren = {
  ApiInvoicesIdRoute: ApiInvoicesIdRoute,
}

const ApiInvoicesRouteWithChildren = ApiInvoicesRoute._addFileChildren(
  ApiInvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiInvoicesRoute: ApiInvoicesRouteWithChildren,
  InvIdRoute: InvIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRecurringProcessRoute: ApiRecurringProcessRoute,
  ApiWebhooksRazorpayRoute: ApiWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
